# The commented parameters have default values but these defaults can be overridden when enabled

# config for eccosp-artemis
eccosp-artemis: # type of ECP component. Can be ecp-endpoint, ecp-directory, ecp-broker, ecp-artemis
  enabled: true # boolean flag which defines whether the component will be deployed or not
  instance: # array of ECP broker instances - one values file can hold multiple instances
    - name: artemis-eptb2 # name of kubernetes instance
      image: # section for information about Docker image
        name: entsoe/eccosp-artemis # URL to docker image.
        tag: 4.14.0 # Docker image tag - version or 'latest'
#        pullPolicy: IfNotPresent # Pull policy specifies when the image should be pulled, it is possible to use 'Always' so on every pod (re)start is pulled
      replicaCount: 1 # number of replicas - ECCoSP Artemis cluster
      resourcesK8s: # section for CPU and memory specification
        requests: # minimum guaranteed amount of a resource that is reserved for a container
          cpu: 500m # minimum CPU - one CPU = 1000m or 1
          memory: 1Gi # minimum memory for container - 1Gi is equal to 1024 Mi
        limits: # maximum amount of a resource to be used by a container. Should be always higher than application can allocate (xmx)
          cpu: 1000m # maximum CPU
          memory: 5Gi # maximum memory for container - 5Gi is equal to 5120 Mi

      storageData: 1Gi # embedded database and certificates # storage for embedded database and certificates. If external DB is used, the value can be lower
      storageLogs: 256Mi # logs # storage for logs
      sharedStorageSize: 100Mi # if SharedStorage for artemis is used, this amount of storage will be requested
      sharedStorageSizeJournal: 100Mi # if SharedStorage for artemis journal is used, this amount of storage will be requested
      sharedStorageClass: nfs-client # if SharedStorage for artemis is used, this storage class will be used to allocate shared storage resources
      sharedStorageClassJournal: nfs-client # if SharedStorage for artemis journal is used, this storage class will be used to allocate shared storage resources
      #sharedStorageAccessMode: ReadWriteMany # sharedStorageAccessMode class
      #storageLogsSize: 64Mi # size of logs storage
      keepLogsAfterRestart: true # boolean flag - indicates if Artemis logs are persisted after pod restart, default value false
      livenessProbe: false # automatic restart if pod is not in health state, default value false
      readinessProbe: true # Artemis pod will not started before readiness probe is fulfilled - check of availability of external DB
      useSharedStorageForConfiguration: true # if enabled, all replicas of this pod will use shared storage for configs and certificates
      useSharedStorageForJournal: true # if enabled, all replicas of this pod will use shared storage for journal
      prometheusEnabled: true #boolean flag - indicates if Prometheus metrics is enabled

      artemisKeystoreLocation: /opt/eccosp-artemis/etc/keystore.jks
      artemisKeystorePassword: password

      service: # section for definition of services exposed within kubernetes environment
        type: LoadBalancer # Default service type is LoadBalancer
#        http: # protocol used for accessing GUI - can be http or https
#          port: 8162 # port used for exposing HTTP(S) service
        https: # protocol used for accessing GUI - can be http or https
          port: 8161 # port used for exposing HTTP(S) service
        amqps: # protocol used for connection on AMQP interface of Artemis - can be AMQP or AMQPS
          port: 5672 # port used for exposing AMQP(S) service
      ingress: # an object that allows access to Kubernetes services from outside the Kubernetes cluster.
        enabled: false # boolean flag for enable/disable ingress, default value false
#        apiVersion: networking.k8s.io/v1 # Specifies the api version of ingress resource
#        contextPath: / # context path for ingress, default value '/'
#        host: eccosp-artemis.eptb2.eccosp # URL on which the ECCoSP Artemis is exposed. Address needs to be aligned with hosting.
#        tls: # section for TLS definition for HTTPS connection to ingress
#          secretName: tls-secret  # secret where TLS certificate is stored
#        annotations: # ingress annotations section
#          kubernetes.io/ingress.class: nginx # ingress annotations - use nginx
#          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # important for remote host tunelling
#          nginx.ingress.kubernetes.io/ssl-passthrough: 'true' # important for remote host tunelling

      # The naming convention for configuration files name and parameters is camelCase instead of 'dot case format'.
      # Mapping of Helm values to ECCoSP Artemis configuration file is available in config map ./eccosp-artemis/templates/configMap.yaml
      brokerXml: # stands for broker.xml file
        default: # parent for default Artemis configuration
          ecpComponentCode: artemis-eptb2 # Artemis identification code in ECP network (EIC) for Audit logging

        addressSettings: # parent for Artemis address settings configuration
          defaultConfigurationEnabled: true # if true, default address settings configuration is enabled
      env:  # stands for env file
#        heapDumpPath: # path to java heap dump file
        resourcesJvm: # memory allocation for Artemis component
          xms: 128M # lower bound of java heap memory size
          xmx: 4G # upper bound of java heap memory size

      artemisUsers: # artemis-users.properties
        - login: endpoint # username for Artemis console
          password: password # password for Artemis console
        - login: toolbox # username for Artemis console
          password: password # password for Artemis console

#      volumeMounts:  # volume mounts - can be used for mapping config files or storages
#        - name: config  # name of volume mounts for config
#          subPath: login.config  # name of configuration file
#          mountPath: /opt/eccosp-artemis/etc/login.config # path where config file will be mounted

#      configMap: # config maps array
#        - subPath: login.config # name of config file/volume mount
#          content: |- # content is shifted by two spaces
#            /*
#              * Licensed to the Apache Software Foundation (ASF) under one or more
#              * contributor license agreements.  See the NOTICE file distributed with
#              * this work for additional information regarding copyright ownership.
#              * The ASF licenses this file to You under the Apache License, Version 2.0
#              * (the "License"); you may not use this file except in compliance with
#              * the License.  You may obtain a copy of the License at
#              *
#              * http://www.apache.org/licenses/LICENSE-2.0
#              *
#              * Unless required by applicable law or agreed to in writing, software
#              * distributed under the License is distributed on an "AS IS" BASIS,
#              * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#              * See the License for the specific language governing permissions and
#              * limitations under the License.
#              */

#             activemq {
#                org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule required
#                    debug=false
#                    reload=true
#                    org.apache.activemq.jaas.properties.user="artemis-users.properties"
#                    org.apache.activemq.jaas.properties.role="artemis-roles.properties";
#             };


# See ECP Kubernetes Guide, Shared Folder Configuration – Custom Volume Mounts
#      volumeClaimTemplates:
#        - metadata:
#            name: cd # volume name
#          spec:
#            accessModes: [ "ReadWriteMany" ] # storage of type ReadWriteMany
#            storageClassName: nfs-storage # name of storage class - needs to be provided by Kubernetes administrator
#            resources:
#              requests:
#                storage: 512Mi # request for storage size

# global config
global: # global config
  storage: # storage section
    class: standard # storage class – needs to be provided by Kubernetes cluster administrator
  imagePullSecrets: # secrets which hold information about login to docker repository
    - name: regcred # name of secret – name is defined by Kubernetes cluster administrator
