{{- range $i, $instance := .Values.instance }}
{{- if $instance.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{$.Release.Namespace}}-{{ $.Chart.Name }}-{{$instance.name}}-svc
  labels:
    backup.component.name: {{ $.Release.Name }}
    app: {{$.Release.Namespace}}-{{ $.Chart.Name }}-{{$instance.name}}
{{- with $instance.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ $instance.service.type }}
  ports:
    {{- if $instance.service.http }}
    - name: http
      port: {{ $instance.service.http.port }}
      protocol: TCP
    {{- end}}
    {{- if $instance.service.https }}
    - name: https
      port: {{ $instance.service.https.port }}
      protocol: TCP
    {{- end}}
    {{- if $instance.service.amqp }}
    - name: amqp
      port: {{ $instance.service.amqp.port }}
      protocol: TCP
    {{- end}}
    {{- if $instance.service.amqps }}
    - name: amqps
      port: {{ $instance.service.amqps.port }}
      protocol: TCP
    {{- end}}

  selector:
    app: {{$.Release.Namespace}}-{{ $.Chart.Name }}-{{$instance.name}}
{{- if $instance.service.loadBalancerIP }}
  loadBalancerIP: {{ $instance.service.loadBalancerIP }}
{{- end }}
---
{{- end }}
{{- range $j, $item := $instance.services }}
{{- toYaml $item | nindent 0 }}
---
{{- end }}
{{ end }}